### PR TITLE
Delete cookie to prevent endless refreshing loops

### PR DESCRIPTION
**Pull request by FliegenKLATSCH**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please provide more information about the exact problem and error case

**Comment by FliegenKLATSCH** [comment]
If the cookie is invalid it ends up in an endless loop:

```
Alexa-Remote: Authentication checked: false
Alexa-Remote: Cookie was set, but authentication invalid
Alexa-Remote: Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Alexa-Remote: Use as Login-Amazon-URL: amazon.de
Alexa-Remote: Use as Base-URL: layla.amazon.de
Alexa-Remote: cookie was provided
Alexa-Remote: Sending Request with {"host":"layla.amazon.de","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
Alexa-Remote: Response: Closed
Error: Error while checking Authentication: Error: COnnection Closed
    at /.../node_modules/alexa-remote2/alexa-remote.js:153:49
    at /.../node_modules/alexa-remote2/alexa-remote.js:889:24
    at ClientRequest.<anonymous> (/.../node_modules/alexa-remote2/alexa-remote.js:866:17)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketCloseListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
Alexa-Remote: Response: No body
Alexa-Remote: Authentication checked: false
```

**Comment by SvenXP** [comment]
Could it be that this has anything to do that the node-red version of alexa-remote (node-red-contrib-alexa-remote2 or node-red-contrib-alexa-cakebaked) is spamming requests to amazon server? (in my case layla.amazon.de).
Like 5,522 in 15 minutes?

**Comment by Apollon77** [comment]
No, but if you use a alexa2-remote lib < 3.7 then this efect could happen because of recent amazon changes. fix in 3.7.x

**Comment by Apollon77** [comment]
@FliegenKLATSCH please update to 3.7.x of lib and recheck. if happens again please send updated error

**Comment by SvenXP** [comment]
node-red-contrib-alexa-cakebaked was updated to 3.7.1 and the requests are gone. Thank you guys :-)

**Comment by Apollon77** [comment]
Please post log of that effect. And BTWE the last update was "special" and I hop you read the changelog, also because it was a major update. So I can not assume it is "the same"

**Comment by FliegenKLATSCH** [comment]
I found another solution now with Alexa routines, not using this library anymore.

**Pull request closed without merging**
