### PR TITLE
Fix check on success status code

### PR DESCRIPTION
**Pull request by FliegenKLATSCH**

### CODE REVIEW

**Comment by Apollon77** [comment]
Ok, great change, will accept it ... but ... whats the effective difference (beside better understandable) ? ;-)

**Comment by FliegenKLATSCH** [comment]
It actually works?!?

**Comment by Apollon77** [comment]
sure :) Why it should not? % is division without rest, in this case 200..299 % 100 = 2

**Comment by FliegenKLATSCH** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder

**Comment by Apollon77** [comment]
ooohh yes you are right ... hhuuups ;-))

**Pull request merged**
