### PR TITLE
reworked getList and getLists

### PR DESCRIPTION
**Pull request by Zefau**
- reworked getList and getLists
- added Emitter for lists
- added Emitter for any command

### CODE REVIEW

**Comment by Zefau** [comment]
Subsequent pr for ioBroker.alexa2 adapter will follow

**Comment by Zefau** [comment]
Please note that parameter `completed` has to be omitted in order to retrieve both `true` and `false`.

**TEST CASE**
```js
alexa.init(options, (err) => {
	alexa.getLists((err, res) => {
		console.log(res.todo.length);
		console.log(res.shopping.length);
	});
});
```

**Comment by Zefau** [comment]
Sorry, I'm too quick. I forgot that I have to consider `setList` as well. I will come back with a better and stronger pr :-D

**Comment by Apollon77** [comment]
Cool. Thank you. Can not await it ;-))

**Pull request closed without merging**
