### PR TITLE
removing TuneIn related functionality 

### PR DESCRIPTION
**Pull request by jamesanse**
Tunein  playback always fail and do not appear to work. Lets get rid of functions related to TuneIn

### CODE REVIEW

**Comment by keleric** [comment]
+1 This just causes confusion

**Comment by klysyk** [comment]
+1

**Comment by Apollon77** [comment]
Guys, I'm honestly not too sure that it "do not work". A fast test with tuneinSearch gave a propr response ... yes afterwards the "setTuneIn" gave an error from the API ... But that might just ean they changed something.

So this seems more a "issue to research whats changed" then a "was removed by Amazon" topic ... So I will not merge this for now, but create an issue

**Comment by Apollon77** [comment]
PS: If you find time to sniff Alexa app traffic to compare have fun ... else I neds to see when I find time

**Pull request closed without merging**
