### PR TITLE
cookie refresh patch

### PR DESCRIPTION
**Pull request by sleuth255**
Automatic cookie refresh wasn't working until I did this change.  Also want to add more description around "no body" error.

### CODE REVIEW

**Comment by Apollon77** [comment]
Is this working? You write the variable in two different cases. And why adding the headers the to the response?

**Comment by sleuth255** [comment]
Yes it is working.  I wasn’t getting an auto cookie refresh until I made the two changes.  Now it is automatically refreshing according to the settings given or 7 days if no settings are given. 

 

Also I’m requesting to add headers to error response because with the US endpoints, I still have the “no body” error returned after 24 hours or so.  I’m now using your alexa-remote as a dependency.  The error code is 401 by the way and the headers look like this:

 

{"content-length":"0","connection":"close","server":"Server","date":"Tue, 24 Dec 2019 14:27:20 GMT","cache-control":"no-transform, no-store","x-amz-rid":"T3Y517CNS373G35S52CH","vary":"Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","x-cache":"Error from cloudfront","via":"1.1 bc779a771e58cc6656070a41635de578.cloudfront.net (CloudFront)","x-amz-cf-pop":"ORD51-C2","x-amz-cf-id":"nRrOWYpExvAqbXc3tbGwj0IpE5D_TDe06ltV3x67083WcUOkKp67wA=="}

 

Interesting that “Error from cloudfront” pops up when the problem starts.  I don’t get this error when I get devices, only when I use sendsequence to speak or announce.  This may be related to the fix above since another app that uses the api (smartthings “Echo Speaks” app) refreshes the cookie every 24 hours.

 

I’ve been debugging this for a while and it’s tedious to keep having to add the headers code after you push updates.  Currently testing with alexa.amazon.de to see if it’s an issue with cloudfront at US endpoints.

**Comment by Apollon77** [comment]
Ok i will check this. Should be error 401 not enough to trigger the refresh? 

Unused refresh with 7 days and everything is working.  Very strange.

**Comment by sleuth255** [comment]
Thanks!  The changes to lines 163 and 169 will definitely fix the “no auto-refresh” issue.   

 

As far as the 401 error goes, also strange is the fact that when the problem is occurring, the getDevices function works but the sendSequenceCommand function using “announcement” or “speak” (haven’t tried any others) returns the 401 error.

 

I have also called alexa.init after receiving the 401 error but that hasn’t corrected the problem.  Not sure if I had params correct on this attempt though so still testing.  I’ve also tried swapping the endpoint from alexa.amazon.com to pitangui.amazon.com (by doing an alexa.init with alexaServiceHost changed) after receiving the 401 error, but this has no effect on the problem either.

 

Waiting to see if I encounter the problem while using alexa.amazon.de.  Results on this in a few days…  

 

Debugging this issue is time consuming because the problem only occurs after a minimum of 24 hours have passed.  I’ve also seen it go for as long as 7 days before the problem occurs as well.

**Comment by Apollon77** [comment]
My First question was: you use two different variables:


options.RefreshCookieInterval and


options.refreshCookieInterval

This can not really work out ...

**Comment by sleuth255** [comment]
Ahhh… missed that.  refreshCookieInterval is correct in both cases and is what I tested.

**Comment by sleuth255** [comment]
will do another pull request

**Comment by sleuth255** [comment]
I’m really beginning to suspect that this is a bug at Amazon’s end which manifests itself on US endpoints.

**Pull request closed without merging**
