### PR TITLE
Add skill launch function

### PR DESCRIPTION
**Pull request by guilhermelirio**
Hi.
I create to invoke skill function.

How to use:

````
const serialNumer = 'your_device_SN';
const command = 'skill';
const skillId = 'skillId of skill';

Alexa.sendSequenceCommand(serialNumber, command, skillId, function (err, res) {
    console.log("error: " + err)
    console.log("result: " + JSON.stringify(res))
    if (!err && res) {
        console.log("Alexa.sendSequenceCommand is successfull");
    }
});
```

### CODE REVIEW

**Comment by Apollon77** [comment]
hey, thank you, two questions:
1. is there anything that could be content of "input"? or is it always empty?
2. 2. is there any API call or such you saw to "get the skill ids"? maybe also implemtn that? (just as idea)

**Comment by guilhermelirio** [comment]
> 
> 
> hey, thank you, two questions:
> 
>     1. is there anything that could be content of "input"? or is it always empty?
> 
>     2. 1. is there any API call or such you saw to "get the skill ids"? maybe also implemtn that? (just as idea)

1) It depends a lot on the user, as there are skills that one user has and another doesn't, and it also varies from stores, for example: A skill in Brazil usually doesn't have in other countries, but there are multi-language skills, where the skillId Do not change.

2) Yes, I thought about it yesterday, and I will try to implement it.

**Comment by guilhermelirio** [comment]
> 
> 
> Coool,thanks, then I wait a little with release.
> 
> for 1.) ...i meaed content for https://github.com/Apollon77/alexa-remote/pull/125/files#diff-c956782f455430085bc2ceb4e2a7154526b7bdc89434041c34a989d309c1109fR1819

Ahh ok. I honestly didn't see anything there, just empty.

https://github.com/cakebake/node-red-contrib-alexa-remote-cakebaked/blob/0b5a0dfd77e68e6484000a5c0478497b690b371e/nodes/alexa-remote-routine.js#L578

**Comment by Apollon77** [comment]
> Ahh ok. I honestly didn't see anything there, just empty.

kk, thank you for checking

**Comment by guilhermelirio** [comment]
Hi @Apollon77.

I developed the function of searching for all the skills, and I would like you to test there:

How to use:
```
Alexa.getSkills((err, data) => {
    console.log(data);
})
```

**Comment by Apollon77** [comment]
I do not find the time to test that right now ... I will just merge now and we continue from there then

**Comment by Apollon77** [comment]
@guilhermelirio I released 3.9.0 of library ... can you please give it a short check on your side?

**Comment by guilhermelirio** [comment]
> 
> 
> @guilhermelirio I released 3.9.0 of library ... can you please give it a short check on your side?

Off course!

**Pull request merged**
