### PR TITLE
adds the ability to call to check the connection

### PR DESCRIPTION
**Pull request by hive**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hey, sorry for the late response ... The init call is no "CheckConnection" call ... and even then checkWsConnection would be a better name ... but in fact it is the same as init ... I do not really see the benefit of that method?

**Comment by jamie-ento** [comment]
Yeah, I think perhaps how I need to use the library is slightly different then yourself. At times it is possible for the connection to drop  (either network/internet/smart home hardware restart/smart home firmware upgrades etc. 

Being able to check the connection from the remote.js would be really useful a direct call the initWsMqttConnection is actually more of a refresh, killing the existing. 

But I think you are correct, even if the functionality is useful, this is not a good implementation., the callback isn't being used at all. 

What do you think about something simple such as accessor 

```
getConnectionStatus () {
    return (this.alexaWsMqtt && this.alexaWsMqtt.connectionActive)
}
```

**Comment by hive** [comment]
Yeah, I think perhaps how I need to use the library is slightly different then yourself. At times it is possible for the connection to drop (either network/internet/smart home hardware restart/smart home firmware upgrades etc.

Being able to check the connection from the remote.js would be really useful a direct call the initWsMqttConnection is actually more of a refresh, killing the existing.

But I think you are correct, even if the functionality is useful, this is not a good implementation., the callback isn't being used at all.

What do you think about something simple such as accessor

getConnectionStatus () {
    return (this.alexaWsMqtt && this.alexaWsMqtt.connectionActive)
}

**Comment by Apollon77** [comment]
isWsMqttConnected will be in next version

**Pull request closed without merging**
